### ISSUE TITLE
Submission ID:615d41e53d37930001407565 validation failed

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/gwas-user-requests#29]
Submission has 116 sumstat files and the error shown is  "formatted_a1071.tsv: There is a problem on our side, please contact gwas-subs@ebi.ac.uk for further advice." and error is there for 74 of the sumstat files.

**Comment by jdhayhurst** [comment]
These are validating fine within approx. 20 mins but it fails to then sync the file to our private FTP within the default 60 min time limit imposed on cluster jobs. However, when it fails, it retries and multiplies the 60 mins by the retry number (up to 5). I am therefore surprised that it unable to complete the sync within 5 hours, but nevertheless that is the case. I could increase the default limit to something 5 hours, so that we have a maximum to 25 hours to complete the sync. However, it's likely that the cause here the number of concurrent requests being made to the FTP server (one per file).

**Comment by Santhi1901** [comment]
Can I restart the submission now?

**Comment by jdhayhurst** [comment]
Hi Santhi, I've kicked it off again so that I can watch the logs - I'll let you know how it goes. I'm trying to figure out why it takes so long to transfer the files.

**Comment by jdhayhurst** [comment]
Hi @Santhi1901, after gwas-sumstats-service#175 (and likely some fixes that that transfer service team made), this submission has now completed successfully.

**Comment by Santhi1901** [comment]
thank you @jdhayhurst . Can I import to curation app now?

**Comment by jdhayhurst** [comment]
@Santhi1901 submission is complete so I think you're good to go
