### ISSUE TITLE
Add a field to indicate which strand the allele is on

### ISSUE THREAD

**Issue by mpage21** [EBISPOT/gwas-user-requests#32]
It would be really helpful to know which strand the allele is on. Sometimes it seems that some of the alleles that are reported are not on the forward strand

**Comment by ljwh2** [comment]
Hi @mpage21, are you looking at the alleles for the top associations in the GWAS Catalog web search? Here, we report the alleles as described by the author in the original paper, which as you observe are not reported consistently. We do additionally pull information on the alleles from Ensembl, which can be found in the top box on the variant page e.g. https://www.ebi.ac.uk/gwas/variants/rs115739169. This can be used to infer strand orientation in some cases, though not for palindromic SNPs. Unfortunately, since strand orientation information is often not reported by authors, we are limited in what we can provide. 
For studies with summary statistics, we do provide harmonised files with all allelles oriented to the forward strand, where possible. You can find more information about summary statistics and the harmonisation process here: https://www.ebi.ac.uk/gwas/docs/methods/summary-statistics
I hope this information is helpful to you
