### ISSUE TITLE
sumstats for 34503513 return “403 forbidden”

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-user-requests#51]
OTAR reported sumstats for 34503513 return “403 forbidden” - why?

**Comment by jdhayhurst** [comment]
It was in the "unpublished" state for a few days. It has since been "republished" and resync'd. @ljwh2 and @sprintell is this definitely the behaviour we want - it seems to cause a lot of confusion.

**Comment by ljwh2** [comment]
We used to only have one status in the Catalog "Unpublished" which covered two scenarios - (1) the study was unpublished for editing and then intended to be republished and (2) the study was permanently unpublished because it was found to be ineligible for the Catalog or the publication was withdrawn. We now have an additional status "Permanently unpublished from Catalog" to cover (2). I suggest we only withdraw the sumstats in scenario (2) (based on the new status "Permanently unpublished from Catalog") and not (1)(status "Unpublished").

**Comment by jdhayhurst** [comment]
created ticket to fix this: https://app.zenhub.com/workspaces/gwas-59df823c4a6feb3786810391/issues/ebispot/goci/632
