### ISSUE TITLE
Studies with GCST code higher than GCST90179469 are not accessible through api 

### ISSUE THREAD

**Issue by ReWard0101** [EBISPOT/gwas-user-requests#70]
Most studies can be accessed through 'https://www.ebi.ac.uk/gwas/rest/api/studies/GCST-code'

But studies with accession code higher than GCST90179469 are not accessible.

https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90179469 shows data as normal
https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90179470 cannot be found
anything above GCST90179469 will not work.

**Comment by ljwh2** [comment]
Hi, we're unable to replicate the issue here. GCST90179470 actually does not exist in the publicly available data, 
see: https://www.ebi.ac.uk/gwas/studies/GCST90179470
However other publicly available studies with higher numbers can be found in the REST API, for example, 
https://www.ebi.ac.uk/gwas/studies/GCST90244660
https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90244660
Note, publicly available GCSTs are not necessarily consecutive, since they are assigned at the point of submission and may be embargoed or require further processing before release. 

Please let us know if you have any examples of publicly available data that cannot be accessed via the REST API

**Comment by ReWard0101** [comment]
Ah so it is not a hard cut off. However the datasets I run into problems with originally are in the range GCST90199621-90201020. 
The data is from this study: https://www.nature.com/articles/s41588-022-01270-1#data-availability

https://www.ebi.ac.uk/gwas/studies/GCST90199621
 - works but there is some missing info

https://www.ebi.ac.uk/gwas/rest/api/studies/GCST90199621 
- doesn't work at all

and then I just went down in the numbers (with big steps) until I found a working link again.

I want to retrieve the reported trait through the /rest/api link.

**Comment by ljwh2** [comment]
I see the problem. When authors make a submission before publication they can choose to make their summary data available immediately, but the submission is not QC'd or annotated by our curators, or indexed in the REST API, until it is associated with a journal article.  Normally this process happens within a couple of weeks of publication, but in this case there was a technical issue with the submission which has prevented us releasing the final version. We are working on this and anticipate the data will become available in ~3 weeks time.  Note reported traits may change slightly at that point for consistency within the Catalog. 

I apologise that the REST API documentation is not clearer on this point, and we will amend this.
